// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANyoguFrIUZBJycT7j-m6imoUCNoU5bEg',
    appId: '1:810311286664:web:113982dfc362011cc0043d',
    messagingSenderId: '810311286664',
    projectId: 'daylog-d365',
    authDomain: 'daylog-d365.firebaseapp.com',
    storageBucket: 'daylog-d365.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk05wiitGVOUxwqNeo32jZY7Bv2uXnvVM',
    appId: '1:810311286664:android:a698c241cb3e3ffcc0043d',
    messagingSenderId: '810311286664',
    projectId: 'daylog-d365',
    storageBucket: 'daylog-d365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NJEQtrttSUnvz6ni9qLHsYPCsfK2iEU',
    appId: '1:810311286664:ios:e25b6146a32b27e5c0043d',
    messagingSenderId: '810311286664',
    projectId: 'daylog-d365',
    storageBucket: 'daylog-d365.appspot.com',
    iosBundleId: 'com.example.daylog',
  );

}